# +------------------+
# | Custom Join Text |
# +------------------+
# Pointlessly released by ThisTNTSquid

include-prefix: true

enable-join-message: true
join-message: '&7[&a+&7] &b%player% &3is online now'
join-message-permissions: 'cjt.joinmessage'

enable-leave-message: false
leave-message: '&7[&c-&7] &b%player% &3went offline'
leave-message-permissions: 'cjt.leavemessage'
